#!/usr/bin/env bash
# shellcheck source-path=source-stubs
# shellcheck source-path=SCRIPTDIR

source /scripts/common
s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

"${s6wrap[@]}" cat <<EOM
Hardware information:
Machine:   $(uname -m)
Processor: $(uname -p)
Platform:  $(uname -i)
EOM
